# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bootstrap 4 CDN Theme
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A simple mobile first theme without hosting the css...
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. https://example.com
lang: en # language can also be set on a per page basis. Primary use right now is only for <html lang="">
google_analytics: "" # UA-XXXXX-Y your Google Analytics tracking ID.
# Build settings
markdown: kramdown
theme: jekyll-theme-bootstrap4-navbar-cdn
permalink: /:title/
navbar: light          # other option dark
navbar-bg: light       # other option dark
navbar-fixed-top: true # if true, also check _sass/bootstrap4-cdn.scss padding top
plugins:
  - jekyll-feed